sensor:

* platform: homeassistant
  entity_id: sensor.temp_living_room_temperature
  id: living_room_temperature
  on_value:

  * lvgl.label.update:
    id: temperatures
    text:
    format: "%d° / %d°"
    args:
    - !lambda 'return (int)round(id(outdoor_temperature).state);'
    - !lambda 'return (int)round(x);'

* platform: homeassistant
  entity_id: sensor.outdoor_temperature
  id: outdoor_temperature

binary_sensor:

* platform: homeassistant
  id: Bmabu_P1S_power
  entity_id: switch.bambu_p1s
  trigger_on_initial_state: true
  on_state:
  then:
  - lvgl.widget.update:
  id: printer_power_button
  state:
  checked: !lambda return x;

* platform: homeassistant
  id: filament_dryer
  entity_id: switch.filament_dryer
  trigger_on_initial_state: true
  on_state:
  then:
  - lvgl.widget.update:
  id: filament_heater_button
  state:
  checked: !lambda return x;

* platform: homeassistant
  id: ceiling
  entity_id: light.ceiling
  trigger_on_initial_state: true
  on_state:
  then:
  - lvgl.widget.update:
  id: storage_lights_button
  state:
  checked: !lambda return x;
